services:

  # Uncomment if testing postgres db locally
  # db:
  #   image: postgres:17
  #   restart: always
  #   environment:
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: secret
  #     POSTGRES_DB: postgres
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data

  backend: 
    build: 
      context: backend
      # target: development
    ports: 
      - 8080:8080

  frontend: 
    build: 
      context: frontend
      # target: development
    command: npm run dev
    ports: 
      - 3000:3000

secrets:
  env:
    file: /backend/.env

volumes:
  pgdata:
