"""initial migration

Revision ID: dd683ff7b9b6
Revises: 
Create Date: 2025-02-13 23:23:41.332438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd683ff7b9b6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_item_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(), nullable=True)) # NOTE: if you want to have a new column have a default value, use default=

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_item_table', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
